# Welcome! Take a look at the code below, starting with #1. 
# What type of error does this produce and why?

# ERROR 1:
# result = 10 / 0  
# print("This will not be printed due to the crash.")

# ERROR 2:
# result = "10" + 5
# print(result) 
# print("This will not be printed due to the crash.")

# ERROR 3:
# print(unknown_variable) 
# print("This will not be printed due to the crash.")

# ERROR 4:
# lst = [1, 2, 3]
# print(lst[5])  
# print("This will not be printed due to the crash.")

# ERROR 5:
# d = {"name": "Dylan"}
# print(d["age"]) 
# print("This will not be printed due to the crash.")

# ERROR 6: 
# num = int("Hello")  
# print("This will not be printed due to the crash.")

# ERROR 7:
# console.log("Hello Console!")
# print("This will not be printed due to the crash.")


